def get_default_brand_config() -> dict:
    return {
        "brand_name": "ООО «Газпромтранс»",
        "slogan": "Энергия движения. Надежность маршрута.",
        "personality": ["Надежный", "Индустриальный", "Технологичный"],
        "colors": {
            "foundation": "#0077C8",
            "corporate": "#003D73",
            "technical": "#66B5E8",
            "atmosphere": "#CFE6F7",
            "steel": "#7D8793",
            "graphite": "#2B2F36",
            "background": "#FFFFFF",
        },
        "gradients": {
            "primary": "linear-gradient(135deg, #0077C8 0%, #003D73 100%)",
            "light": "linear-gradient(135deg, #66B5E8 0%, #FFFFFF 100%)",
            "atmosphere": "linear-gradient(135deg, #EAF1F8 0%, #0077C8 100%)",
            "slide_light": "linear-gradient(135deg, #FFFFFF 0%, #EAF4FC 48%, #CFE6F7 100%)",
            "slide_dark": "linear-gradient(135deg, #003D73 0%, #0077C8 55%, #2B2F36 100%)",
        },
        "typography": {
            "headline": "DIN Condensed Bold, Arial Narrow, Arial, sans-serif",
            "subhead": "DIN Pro Medium, Arial, sans-serif",
            "body": "DIN Pro Regular, Arial, sans-serif",
            "fallback": "Arial, sans-serif",
        },
        "iconography": {
            "style": "linear corporate icons",
            "stroke": "#0077C8",
            "stroke_width": 2,
            "allowed_icons": [
                "locomotive",
                "wagon",
                "route",
                "gas_flame",
                "dispatch",
                "customs",
                "safety",
                "analytics",
                "document",
                "calendar",
                "shield",
                "map",
            ],
        },
        "visual_language": {
            "mood": "индустриальный, технологичный, надежный, чистый корпоративный",
            "image_themes": [
                "железнодорожная логистика",
                "локомотивы",
                "цистерны",
                "маршруты",
                "северная инфраструктура",
                "технологии управления",
                "промышленная безопасность",
            ],
            "forbidden": [
                "случайные яркие цвета",
                "мультяшность",
                "кислотные градиенты",
                "английские подписи",
                "перегруженный фон",
                "иконки разных стилей",
            ],
        },
        "layout_rules": {
            "slide_width": 1600,
            "slide_height": 900,
            "logo": {"x": 88, "y": 52, "width": 430, "height": 110},
            "content": {"x": 88, "y": 182, "width": 1424, "height": 600},
            "footer_topic": {"x": 88, "y": 826, "width": 1220, "height": 34},
            "footer_page": {"x": 1320, "y": 826, "width": 190, "height": 34},
        },
    }
